export const Candidate = {
  Name: "",
  Email: "",
  phone_number: "",
  Department: "",
  College: "",
  communicationScore: 0,
  innovationScore: 0,
  fireInBellyScore: 0,
  deductionPoints: 0,
  overallscore: 0,
  detailedAnalysis: {},
  behavioralAnalysis: {},
  recommendation: "",
  summary: "",
};
